### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ChunkyProgrammer** [efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube#11]
How do i post comments on this app???

blocked by https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube/pull/16
blocked by https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube/pull/17
blocked by https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube/pull/16
depends on blocked by https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube/pull/15
depends on 

depends on https://github.com/privacyguides/privacyguides.org/pull/777
depends on https://github.com/privacyguides/privacyguides.org/pull/774

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by #10

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by #10

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by #10

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by #10

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by #14

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by #11

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by #11

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by #11

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube/issues/10

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube/issues/10

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by #13

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
depends on #13

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube/pull/16

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This PR/issue depends on:
* ~~efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube#16~~
* efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube#17

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by #16

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
blocked by #13
