### ISSUE TITLE
[Feature Request]: add youtube account 

### ISSUE THREAD

**Issue by ChunkyProgrammer** [efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube#24]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Please

### Proposed Solution

Please

### Alternatives Considered

Please

### Issue Labels

visual improvement

### Additional Information

Please

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hmm it seems that u haven't filled in the template correctly. I would like some more info on this before i start working on it.
